spring.application.name=productService
spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=root
spring.datasource.password=1981
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.threads.virtual.enabled=true

spring.kafka.bootstrap-servers=localhost:9092spring.kafka.consumer.group-id=order-service-groupspring.kafka.consumer.auto-offset-reset=earliestspring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializerspring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializerspring.kafka.consumer.properties.spring.json.trusted.packages=org.example.*server.port=8082#

server.port=8082
grpc.client.userService.address=dns:///user-service:9090
grpc.client.userService.negotiation-type=plaintext

grpc.server.port=9090
grpc.server.reflection-service-enabled=true

spring.data.redis.host=redis-server
spring.data.redis.port=6379